services:
  app:
    image: mattposch/${APP_NAME}:main
    container_name: ${APP_NAME}
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_TLS_REJECT_UNAUTHORIZED=${SMTP_TLS_REJECT_UNAUTHORIZED}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - SIGNIN_URL_BASE=${SIGNIN_URL_BASE}
    networks:
      - apps_proxy
    expose:
      - "3000"

networks:
  apps_proxy:
    external: true