services:
  app:
    image: mattposch/${APP_NAME}:main
    container_name: ${APP_NAME}
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - apps_proxy
    expose:
      - "3000"

networks:
  apps_proxy:
    external: true